### PR TITLE
Only support direct inheritance from Params

### LINKED ISSUE #2: Class attributes aren't present in subclasses
This breaks the Params `__init__` function when you subclass it twice

```
def __init__(self, **kwargs):
        cls = type(self)
        for key, value in kwargs.items():
            if not key in cls.__dict__:
                raise KeyError(f'{cls.__name__} does not take {key} as an argument')
            setattr(self, key, value)
        _check_for_required_arguments(cls, kwargs)
```
ex.

```
class A(Params):
    x = BoolParams(default=True, help='')

class B(A):
    y = IntParam(help='')

# raises a KeyError
b = B(x=False)
```

### PR DESCRIPTION
**Pull request by schuylerfried**
Closes #2

### CODE REVIEW

**Comment by schuylerfried** [comment]
> This seems not future-proof

I agree that it is definitely a band-aid, but the behavior is currently undefined when you don't have direct inheritance. Class attributes are not inherited... I think it'll be fairly easy to remove this in the future if we want to build in support, but it doesn't seem useful now.

**Comment by jonward-rigetti** [comment]
Would it be much more difficult to make class attributes inherited? 
This just seems like the thing where someone would go to inherit the class and then be very surprised that they are not allowed to.

**Comment by schuylerfried** [comment]
It would require a refactor of most of the code (the way we iterate through the class attributes), which is fine, but I don't think it's necessary for now. Can you think of a use case?

**Comment by schuylerfried** [comment]
Alright - after speaking with @jonward-rigetti, I'm going to push some documentation to make it extremely clear that only direct inheritance is supported, then merge

**Pull request merged**
