### PR TITLE
Unit refactor

### LINKED ISSUE #43: += not blocked from params with units
If a param has a certain unit, += is broken

Ex.
```python
class A:
    b = FloatParam(help='float', unit='ns')

a = A()
a.b = 2
print(a.b)  # prints 2e-9
a.b += 2
print(a.b)  # prints (2e-9 + 2) * 1e-9
```

There's no way to block the `__iadd__` method for this case because what's actually being called is the `__iadd__` method on a.b, which is a float. The alternative is to use si_set:

```python
a.si_set('b', a.b + 2e-9)
```

but this isn't that nice. Alternatives are to remove units from the `__get__` and `__set__` methods and only use them for parsing from the command line or from a yaml.

### PR DESCRIPTION
**Pull request by schuylerfried**
Refactor unit handling to only happen once after parsing and not during get operations

closes #43

### CODE REVIEW

**Comment by deanna-abrams** [comment]
So unit magic will only happen from command line to object, and never again?

**Comment by schuylerfried** [comment]
> So unit magic will only happen from command line to object, and never again?

Yes - that's the goal

**Comment by deanna-abrams** [comment]
> > So unit magic will only happen from command line to object, and never again?
> 
> Yes - that's the goal

what about when going to and from json-serializable params?

**Comment by deanna-abrams** [comment]
I'm a little confused about the desired behavior here.

When you initialize an instance of a class that has param `t` with default of 60 and units of MHz, should `class.t` be 60 or 60e6?

if it's the former (i.e. you should have a default of 60e6 if you want it in MHz), then running
```
parser = to_argparse(MySummer)
args = parser.parse_args([])
y = from_parsed_args(MySummer, params_namespace=args)[0]
```
Where MySummer has an attribute t with units of MHz, and a default of 60e-9,

will double parse the units b/c . Once in `parser.parse_args` because it will fill in with the default 60e-9, and once in `from_parsed_args` because we're adding the units when we call `_unflatten_param_class`.

However
```
parser = to_argparse(MySummer)
args = parser.parse_args(['t', '60'])
y = from_parsed_args(MySummer, params_namespace=args)[0]
```
will give us the correct units in `y.t`


This points to us having a default of 60 with units of MHz, but then if you initialize the class NOT through the parser, there won't be the right units.

**Comment by schuylerfried** [comment]
> I'm a little confused about the desired behavior here.
> 
> When you initialize an instance of a class that has param `t` with default of 60 and units of MHz, should `class.t` be 60 or 60e6?
> 
> if it's the former (i.e. you should have a default of 60e6 if you want it in MHz), then running
> 
> ```
> parser = to_argparse(MySummer)
> args = parser.parse_args([])
> y = from_parsed_args(MySummer, params_namespace=args)[0]
> ```
> 
> Where MySummer has an attribute t with units of MHz, and a default of 60e-9,
> 
> will double parse the units b/c . Once in `parser.parse_args` because it will fill in with the default 60e-9, and once in `from_parsed_args` because we're adding the units when we call `_unflatten_param_class`.
> 
> However
> 
> ```
> parser = to_argparse(MySummer)
> args = parser.parse_args(['t', '60'])
> y = from_parsed_args(MySummer, params_namespace=args)[0]
> ```
> 
> will give us the correct units in `y.t`
> 
> This points to us having a default of 60 with units of MHz, but then if you initialize the class NOT through the parser, there won't be the right units.

Yeah that's a good point. Ideally, the default will be in SI units as well. I think there's an easy fix for this, which is calling unconvert_si_unit on the param.default just before adding it to the argument parser in _add_param_to_parser.

**Pull request merged**
